### ISSUE TITLE
Баги и визуальные недочеты

### ISSUE THREAD

**Issue by f1van0** [Sib-Game-Jam-div-null/Goose-Defence#6]
- Передние башни иногда не могут улучится при нажатии на соответствующую кнопку при этом снимается игровая валюта (закономерность: улучшая башню может появляться ошибка, так как гуси после своего появления зацикливаются на башне. Чаще встречалось, когда окно улучшений было закрыто);
- Иногда появляется белый гусь, который не может двигаться вперед;
- После нейтрализации гуся-босса игра не заканчивается;
- После рестарта игры гусь-босс не появляется, а игровая валюта увеличивается быстрее;
- Гуси появляются с краю и попадают в камеру, точку появления необходимо разместить немного правее;
- У бурых гусей после исчезновения повторяется анимация (происходит мерцание в конце).

**Comment by Optifun** [comment]
- [x] Передние башни иногда не могут улучшится при нажатии на соответствующую кнопку при этом снимается игровая валюта (закономерность: улучшая башню может появляться ошибка, так как гуси после своего появления зацикливаются на башне. Чаще встречалось, когда окно улучшений было закрыто);
- [x] Иногда появляется белый гусь, который не может двигаться вперед;
- [x] После нейтрализации гуся-босса игра не заканчивается;
- [x] После рестарта игры гусь-босс не появляется, а игровая валюта увеличивается быстрее;
- [x] Гуси появляются с краю и попадают в камеру, точку появления необходимо разместить немного правее;
- [x] У бурых гусей после исчезновения повторяется анимация (происходит мерцание в конце).
- [x] Босс имеет высокую скорость передвижения при спавне на 30 волне.

**Comment by Optifun** [comment]
Баги исправлены в #7.
